<a href="https://colab.research.google.com/github/Saisantosh2004/DLforCV/blob/main/TensorsAndVariables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
tensor_indexed=tf.constant([1,2,3,4,4,5])

In [3]:
print(tensor_indexed[0:5])

tf.Tensor([1 2 3 4 4], shape=(5,), dtype=int32)


In [4]:
print(tensor_indexed[1:5])

tf.Tensor([2 3 4 4], shape=(4,), dtype=int32)


In [6]:
tensor_two_d=tf.constant([
    [1,2,0],
    [3,4,5],
    [5,6,7],
 ])

print(tensor_two_d[0:3,0:2])

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [7]:
print(tensor_two_d[2,1:3])

tf.Tensor([6 7], shape=(2,), dtype=int32)


In [8]:
print(tensor_two_d[...,1])

tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [19]:
tensor_three_d=tf.constant([
        [[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]]
)
#print(tensor_three_d[ 0 , 0 , 0])
#print(tensor_three_d[ 0 , 0 , -1])
print(tensor_three_d[ 0:1 , ... , :])
#print(tensor_three_d[ 0 , 0 , -1])

tf.Tensor(
[[[1 2]
  [3 4]]], shape=(1, 2, 2), dtype=int32)


In [20]:
x = tf.constant([-2.25, 3.25])

In [21]:
x

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-2.25,  3.25], dtype=float32)>

In [22]:
tf.abs(x)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [23]:
x = tf.constant([[-2.25 + 4.75j], [-3.25 + 5.75j]])
tf.abs(x)

<tf.Tensor: shape=(2, 1), dtype=float64, numpy=
array([[5.25594901],
       [6.60492241]])>

In [29]:
x1 = tf.constant([1, 2, 3, 4, 5])
x2= tf.constant([1, 2, 3, 4, 5])
tf.add(x1, x2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 2,  4,  6,  8, 10], dtype=int32)>

In [30]:
tf.math.multiply(x1,x2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25], dtype=int32)>

In [34]:
x3 = tf.constant([5])
tf.add(x1, x3)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 6,  7,  8,  9, 10], dtype=int32)>

In [ ]:
B = tf.constant([[2, 20, 30, 3, 6], [3, 11, 16, 1, 8],
                 [14, 45, 23, 5, 27]])
