<a href="https://colab.research.google.com/github/Saisantosh2004/DLforCV/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello world")

Hello world


In [2]:
import tensorflow as tf

In [8]:
tensor3d=tf.constant([
    [[1,2,3],[1,2,3]],
    [[1,2,3],[1,2,3]],
    [[1,2.,3],[1,2,3]],
    [[1,2,3],[1,2,3]]
],dtype=tf.float32)
casted_tensor=tf.cast(tensor3d,dtype=tf.int16)
print(tensor3d)
print(casted_tensor)

tf.Tensor(
[[[1. 2. 3.]
  [1. 2. 3.]]

 [[1. 2. 3.]
  [1. 2. 3.]]

 [[1. 2. 3.]
  [1. 2. 3.]]

 [[1. 2. 3.]
  [1. 2. 3.]]], shape=(4, 2, 3), dtype=float32)
tf.Tensor(
[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]], shape=(4, 2, 3), dtype=int16)


In [49]:
tf.random.set_seed(1234)
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'
tf.random.set_seed(1234)
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'

tf.Tensor([0.1689806], shape=(1,), dtype=float32)
tf.Tensor([0.7539084], shape=(1,), dtype=float32)
tf.Tensor([0.1689806], shape=(1,), dtype=float32)
tf.Tensor([0.7539084], shape=(1,), dtype=float32)


In [4]:
print(tensor3d.shape)

(4, 2, 3)


In [31]:
print(tensor3d.ndim)

3


In [32]:
print(tf.shape(tensor3d))

tf.Tensor([4 2 3], shape=(3,), dtype=int32)


In [9]:
tensor_bool=tf.constant([True,False])

In [10]:
print(tensor_bool)

tf.Tensor([ True False], shape=(2,), dtype=bool)


In [11]:
import numpy as  np

In [12]:
np_array=np.array([1,2,4])

In [13]:
converted_tensor=tf.convert_to_tensor(np_array)

In [14]:
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


In [22]:
eye_tensor=tf.eye(
    num_rows=3,
    num_columns=3,
    batch_shape=[2,4],
    dtype=tf.dtypes.float32,
    name=None,
)
print(eye_tensor)

tf.Tensor(
[[[[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]]


 [[[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]]], shape=(2, 4, 3, 3), dtype=float32)


In [24]:
fill_tensor=tf.fill(
    [2,3,4],5,name=None
)
print(fill_tensor)

tf.Tensor(
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]], shape=(2, 3, 4), dtype=int32)


In [25]:
ones_tensor=tf.ones(
    [5,3],
    name=None
)

In [26]:
print(ones_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(5, 3), dtype=float32)


In [27]:
ones_like_tensor=tf.ones_like(fill_tensor)

In [28]:
print(ones_like_tensor)

tf.Tensor(
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]], shape=(2, 3, 4), dtype=int32)


In [30]:
zeroes_tensor=tf.zeros(
    [5,3],
    name=None
)
print(zeroes_tensor)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(5, 3), dtype=float32)


In [34]:
tf.rank(ones_like_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [42]:
random_tensor=tf.random.normal(
    [3,2],
    mean=100.0,
    stddev=30.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

In [43]:
random_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[109.16075 , 119.58246 ],
       [101.41514 ,  82.46446 ],
       [114.48915 , 116.785866]], dtype=float32)>

In [48]:
random_tensor=tf.random.uniform(
    [5,5],
    minval=0,
    maxval=45,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
random_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1.9007620e+01, 2.3299513e+01, 4.1142509e+01, 1.7135668e+00,
        1.1872434e+01],
       [4.3275070e+01, 2.1744137e+01, 2.5104044e+01, 1.5802588e+01,
        3.2373425e+01],
       [2.8157782e+01, 2.7868141e+01, 2.7680397e-02, 2.1182043e+01,
        3.4466858e+01],
       [3.3346264e+01, 2.4403215e+01, 4.1800690e+01, 2.0773779e+01,
        2.6443823e+01],
       [1.2277710e+01, 1.0251022e+01, 9.4715776e+00, 1.3332559e+01,
        1.7236181e+01]], dtype=float32)>